// <auto-generated />
using System;
using DealerposAPI.DAL;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace DealerposAPI.Migrations
{
    [DbContext(typeof(Context))]
    partial class ContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "8.0.10");

            modelBuilder.Entity("DealerposAPI.Models.Adicionales", b =>
                {
                    b.Property<int>("adicionalId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("descripcion")
                        .HasColumnType("TEXT");

                    b.Property<string>("imagen")
                        .HasColumnType("TEXT");

                    b.Property<float>("precio")
                        .HasColumnType("REAL");

                    b.Property<int>("productoId")
                        .HasColumnType("INTEGER");

                    b.HasKey("adicionalId");

                    b.ToTable("Adicionales");
                });

            modelBuilder.Entity("DealerposAPI.Models.Ajustes", b =>
                {
                    b.Property<int>("ajusteId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("direccion")
                        .HasColumnType("TEXT");

                    b.Property<string>("email")
                        .HasColumnType("TEXT");

                    b.Property<string>("estado")
                        .HasColumnType("TEXT");

                    b.Property<string>("lectora")
                        .HasColumnType("TEXT");

                    b.Property<string>("moneda")
                        .HasColumnType("TEXT");

                    b.Property<string>("nombreEmpresa")
                        .HasColumnType("TEXT");

                    b.Property<string>("numeroFiscal")
                        .HasColumnType("TEXT");

                    b.Property<string>("pais")
                        .HasColumnType("TEXT");

                    b.Property<string>("propietario")
                        .HasColumnType("TEXT");

                    b.Property<string>("smtpHost")
                        .HasColumnType("TEXT");

                    b.Property<string>("smtpPassword")
                        .HasColumnType("TEXT");

                    b.Property<int?>("smtpPort")
                        .HasColumnType("INTEGER");

                    b.Property<string>("smtpUsername")
                        .HasColumnType("TEXT");

                    b.Property<string>("telefono")
                        .HasColumnType("TEXT");

                    b.Property<string>("tipoFiscal")
                        .HasColumnType("TEXT");

                    b.HasKey("ajusteId");

                    b.ToTable("Ajustes");
                });

            modelBuilder.Entity("DealerposAPI.Models.Autenticaciones", b =>
                {
                    b.Property<int>("autenticacionId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("codigo")
                        .HasColumnType("TEXT");

                    b.Property<string>("dispositivo")
                        .HasColumnType("TEXT");

                    b.Property<string>("estado")
                        .HasColumnType("TEXT");

                    b.Property<string>("fecha")
                        .HasColumnType("TEXT");

                    b.Property<int>("usuarioId")
                        .HasColumnType("INTEGER");

                    b.HasKey("autenticacionId");

                    b.ToTable("Autenticaciones");
                });

            modelBuilder.Entity("DealerposAPI.Models.Caracteristicas", b =>
                {
                    b.Property<int>("caracteristicaId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("descripcion")
                        .HasColumnType("TEXT");

                    b.Property<int>("iconoId")
                        .HasColumnType("INTEGER");

                    b.Property<string>("nombre")
                        .HasColumnType("TEXT");

                    b.Property<int>("productoId")
                        .HasColumnType("INTEGER");

                    b.HasKey("caracteristicaId");

                    b.ToTable("Caracteristicas");
                });

            modelBuilder.Entity("DealerposAPI.Models.Categorias", b =>
                {
                    b.Property<int>("categoriaId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("descripcion")
                        .HasColumnType("TEXT");

                    b.Property<string>("imagen")
                        .HasColumnType("TEXT");

                    b.HasKey("categoriaId");

                    b.ToTable("Categorias");
                });

            modelBuilder.Entity("DealerposAPI.Models.DetalleProductoSucursales", b =>
                {
                    b.Property<int>("detalleProductoSucursalId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<int>("productoId")
                        .HasColumnType("INTEGER");

                    b.Property<int>("sucursalId")
                        .HasColumnType("INTEGER");

                    b.HasKey("detalleProductoSucursalId");

                    b.ToTable("DetalleProductoSucursales");
                });

            modelBuilder.Entity("DealerposAPI.Models.DetalleVentaPagos", b =>
                {
                    b.Property<int>("detalleVentaPagoId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("estado")
                        .HasColumnType("TEXT");

                    b.Property<string>("fecha")
                        .HasColumnType("TEXT");

                    b.Property<string>("metodoPago")
                        .HasColumnType("TEXT");

                    b.Property<float>("montoPagado")
                        .HasColumnType("REAL");

                    b.Property<int>("usuarioId")
                        .HasColumnType("INTEGER");

                    b.Property<int>("ventaId")
                        .HasColumnType("INTEGER");

                    b.HasKey("detalleVentaPagoId");

                    b.ToTable("DetalleVentaPagos");
                });

            modelBuilder.Entity("DealerposAPI.Models.DetalleVentas", b =>
                {
                    b.Property<int>("detalleVentaId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<int>("cantidadProducto")
                        .HasColumnType("INTEGER");

                    b.Property<string>("descripcionProducto")
                        .HasColumnType("TEXT");

                    b.Property<float>("descuentoProducto")
                        .HasColumnType("REAL");

                    b.Property<float>("precioProducto")
                        .HasColumnType("REAL");

                    b.Property<int>("productoId")
                        .HasColumnType("INTEGER");

                    b.Property<int>("ventaId")
                        .HasColumnType("INTEGER");

                    b.HasKey("detalleVentaId");

                    b.ToTable("DetalleVentas");
                });

            modelBuilder.Entity("DealerposAPI.Models.Favoritos", b =>
                {
                    b.Property<int>("favoritoId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<int>("productoId")
                        .HasColumnType("INTEGER");

                    b.Property<int>("usuarioId")
                        .HasColumnType("INTEGER");

                    b.HasKey("favoritoId");

                    b.ToTable("Favoritos");
                });

            modelBuilder.Entity("DealerposAPI.Models.Iconos", b =>
                {
                    b.Property<int>("iconoId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("imagen")
                        .HasColumnType("TEXT");

                    b.Property<string>("titulo")
                        .HasColumnType("TEXT");

                    b.HasKey("iconoId");

                    b.ToTable("Iconos");
                });

            modelBuilder.Entity("DealerposAPI.Models.Productos", b =>
                {
                    b.Property<int>("productoId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<int>("cantidad")
                        .HasColumnType("INTEGER");

                    b.Property<int>("categoriaId")
                        .HasColumnType("INTEGER");

                    b.Property<string>("codigo")
                        .HasColumnType("TEXT");

                    b.Property<float>("costo")
                        .HasColumnType("REAL");

                    b.Property<string>("descripcion")
                        .HasColumnType("TEXT");

                    b.Property<float>("descuento")
                        .HasColumnType("REAL");

                    b.Property<string>("diagarantia")
                        .HasColumnType("TEXT");

                    b.Property<string>("estado")
                        .HasColumnType("TEXT");

                    b.Property<string>("imagen")
                        .HasColumnType("TEXT");

                    b.Property<string>("nombre")
                        .HasColumnType("TEXT");

                    b.Property<float>("precio")
                        .HasColumnType("REAL");

                    b.HasKey("productoId");

                    b.ToTable("Productos");
                });

            modelBuilder.Entity("DealerposAPI.Models.Reclamaciones", b =>
                {
                    b.Property<int>("reclamacionId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("descripcion")
                        .HasColumnType("TEXT");

                    b.Property<string>("estado")
                        .HasColumnType("TEXT");

                    b.Property<string>("fecha")
                        .HasColumnType("TEXT");

                    b.Property<string>("respuesta")
                        .HasColumnType("TEXT");

                    b.Property<string>("titulo")
                        .HasColumnType("TEXT");

                    b.Property<int>("usuarioId")
                        .HasColumnType("INTEGER");

                    b.HasKey("reclamacionId");

                    b.ToTable("Reclamaciones");
                });

            modelBuilder.Entity("DealerposAPI.Models.Roles", b =>
                {
                    b.Property<int>("rolId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("descripcion")
                        .HasColumnType("TEXT");

                    b.Property<string>("nombre")
                        .HasColumnType("TEXT");

                    b.HasKey("rolId");

                    b.ToTable("Roles");
                });

            modelBuilder.Entity("DealerposAPI.Models.Sucursales", b =>
                {
                    b.Property<int>("sucursalId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("descripcion")
                        .HasColumnType("TEXT");

                    b.HasKey("sucursalId");

                    b.ToTable("Sucursales");
                });

            modelBuilder.Entity("DealerposAPI.Models.Tarifas", b =>
                {
                    b.Property<int>("tarifaId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<int>("ciudadId")
                        .HasColumnType("INTEGER");

                    b.Property<float>("monto")
                        .HasColumnType("REAL");

                    b.Property<int>("sucursalId")
                        .HasColumnType("INTEGER");

                    b.HasKey("tarifaId");

                    b.ToTable("Tarifas");
                });

            modelBuilder.Entity("DealerposAPI.Models.Usuarios", b =>
                {
                    b.Property<int>("usuarioId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("apellido")
                        .HasColumnType("TEXT");

                    b.Property<int>("ciudadId")
                        .HasColumnType("INTEGER");

                    b.Property<string>("contrasena")
                        .HasColumnType("TEXT");

                    b.Property<string>("direccion")
                        .HasColumnType("TEXT");

                    b.Property<string>("email")
                        .HasColumnType("TEXT");

                    b.Property<int>("estadoId")
                        .HasColumnType("INTEGER");

                    b.Property<string>("imagen")
                        .HasColumnType("TEXT");

                    b.Property<string>("nombre")
                        .HasColumnType("TEXT");

                    b.Property<int>("paisId")
                        .HasColumnType("INTEGER");

                    b.Property<int>("rolId")
                        .HasColumnType("INTEGER");

                    b.Property<string>("sexo")
                        .HasColumnType("TEXT");

                    b.Property<string>("telefono")
                        .HasColumnType("TEXT");

                    b.Property<string>("verificado")
                        .HasColumnType("TEXT");

                    b.HasKey("usuarioId");

                    b.ToTable("Usuarios");
                });

            modelBuilder.Entity("DealerposAPI.Models.Ventas", b =>
                {
                    b.Property<int>("ventaId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<int>("ciudadId")
                        .HasColumnType("INTEGER");

                    b.Property<float>("descuento")
                        .HasColumnType("REAL");

                    b.Property<string>("direccion")
                        .HasColumnType("TEXT");

                    b.Property<string>("email")
                        .HasColumnType("TEXT");

                    b.Property<string>("envio")
                        .HasColumnType("TEXT");

                    b.Property<string>("estadoEntrega")
                        .HasColumnType("TEXT");

                    b.Property<string>("estadoPagado")
                        .HasColumnType("TEXT");

                    b.Property<string>("fecha")
                        .HasColumnType("TEXT");

                    b.Property<float>("impuesto")
                        .HasColumnType("REAL");

                    b.Property<string>("metodoEntrega")
                        .HasColumnType("TEXT");

                    b.Property<string>("nombre")
                        .HasColumnType("TEXT");

                    b.Property<string>("nota")
                        .HasColumnType("TEXT");

                    b.Property<string>("numeroPedido")
                        .HasColumnType("TEXT");

                    b.Property<int>("paisId")
                        .HasColumnType("INTEGER");

                    b.Property<int>("provinciaId")
                        .HasColumnType("INTEGER");

                    b.Property<float>("subtotal")
                        .HasColumnType("REAL");

                    b.Property<string>("telefono")
                        .HasColumnType("TEXT");

                    b.Property<string>("tipoVenta")
                        .HasColumnType("TEXT");

                    b.Property<int>("usuarioId")
                        .HasColumnType("INTEGER");

                    b.HasKey("ventaId");

                    b.ToTable("Ventas");
                });

            modelBuilder.Entity("DealerposAPI.Models.Verificaciones", b =>
                {
                    b.Property<int>("verificacionId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("codigo")
                        .HasColumnType("TEXT");

                    b.Property<string>("estado")
                        .HasColumnType("TEXT");

                    b.Property<int>("usuarioId")
                        .HasColumnType("INTEGER");

                    b.Property<string>("vencimiento")
                        .HasColumnType("TEXT");

                    b.HasKey("verificacionId");

                    b.ToTable("Verificaciones");
                });
#pragma warning restore 612, 618
        }
    }
}
