// <auto-generated />
using GeografiaAPI.DAL;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace GeografiaAPI.Migrations
{
    [DbContext(typeof(Context))]
    [Migration("20241113003718_Geo")]
    partial class Geo
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "8.0.10");

            modelBuilder.Entity("GeografiaAPI.Models.Ciudades", b =>
                {
                    b.Property<int>("ciudadId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("descripcion")
                        .HasColumnType("TEXT");

                    b.Property<int>("estadoId")
                        .HasColumnType("INTEGER");

                    b.HasKey("ciudadId");

                    b.ToTable("Ciudades");
                });

            modelBuilder.Entity("GeografiaAPI.Models.Estados", b =>
                {
                    b.Property<int>("estadoId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("descripcion")
                        .HasColumnType("TEXT");

                    b.Property<int>("paisId")
                        .HasColumnType("INTEGER");

                    b.HasKey("estadoId");

                    b.ToTable("Estados");
                });

            modelBuilder.Entity("GeografiaAPI.Models.Paises", b =>
                {
                    b.Property<int>("paisId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("descripcion")
                        .HasColumnType("TEXT");

                    b.HasKey("paisId");

                    b.ToTable("Paises");
                });
#pragma warning restore 612, 618
        }
    }
}
